### ISSUE TITLE
Dependancy Documentation

### ISSUE THREAD

**Issue by CEngelbrecht** [SDSURocketProject/Test-Stand-DAQ#2]
It would be great if there was a running list of dependencies: Python3, PyQt5, paho-mqtt, etc, as well as links and how to install them.

**Comment by alefir** [comment]
I've filed a PR to fix this

**Comment by alefir** [comment]
whoops wrong button

**Comment by colanzio5** [comment]
Ill add dep to readme.md and install instructions for mosquitto broker and python scripts and submit them with my other pull request

**Comment by alefir** [comment]
Resolved with #4
